"""empty message

Revision ID: 2d0248705ede
Revises: a53847191429
Create Date: 2023-11-02 10:59:42.093740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0248705ede'
down_revision = 'a53847191429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theStory', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('storyPrompt', sa.String(), nullable=True))
        batch_op.drop_column('prompt')
        batch_op.drop_column('story')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('prompt', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('storyPrompt')
        batch_op.drop_column('theStory')

    # ### end Alembic commands ###
