"""empty message

Revision ID: a53847191429
Revises: e2a2d2ce8fb0
Create Date: 2023-11-02 10:55:43.868505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53847191429'
down_revision = 'e2a2d2ce8fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('story', sa.String(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('story')
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###
