"""empty message

Revision ID: d0ecd2d54d02
Revises: 2d0248705ede
Create Date: 2023-11-07 10:44:43.496985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ecd2d54d02'
down_revision = '2d0248705ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageFromNewStory', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('imageFromNewStory')

    # ### end Alembic commands ###
