"""empty message

Revision ID: e2a2d2ce8fb0
Revises: 2145f3c213e1
Create Date: 2023-11-02 10:30:20.032617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a2d2ce8fb0'
down_revision = '2145f3c213e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storyFromImage', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('storyFromImage')

    # ### end Alembic commands ###
